package UI;

import DAO.UserDAO;
import Model.NhaXuatBan;
import Model.Sach;
import Model.TheLoai;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author luongtopp
 */
public class Manager extends javax.swing.JFrame {

    /**
     * Creates new form Manager
     */
    public Manager() {
        initComponents();
        hienThiBangSach();
        hienThiBangTheLoai();
        hienThiBangNhaXuatBan();
        resetDuLieuSach();
        tblSach.setComponentPopupMenu(jPopupMenu1);
        pnlSuaSach.setVisible(false);
        pnlSuaTheLoai.setVisible(false);
        pnlSuaNhaXuatBan.setVisible(false);

    }

    private void resetDuLieuSach() {
        cboNhaXuatBan.setSelectedIndex(-1);
        cboTheLoai.setSelectedIndex(-1);
        txtTenSach.setText("");
        txtGiaTien.setText("");
        pnlSuaSach.setVisible(false);
        pnlThemSach.setVisible(true);

    }

    private void resetDuLieuTheLoai() {
        txtTenTheLoai.setText("");
    }

    private void resetDuLieuNhaXuatBan() {
        txtTenNhaXuatBan.setText("");
    }

    private void hienThiBangSach() {
        DefaultTableModel model = (DefaultTableModel) tblSach.getModel();
        model.setRowCount(0);
        for (Sach item : new UserDAO().timSach()) {
            model.addRow(new Object[]{
                item.getMaSach(),
                item.getTenSach(),
                item.getTenTheLoai(),
                item.getTenNhaXuatBan(),
                item.getNgayNhap(),
                item.getGiaTien()});
        }

    }

    private void hienThiBangTheLoai() {
        DefaultTableModel model = (DefaultTableModel) tblTheLoai.getModel();
        model.setRowCount(0);
        for (TheLoai item : new UserDAO().timTheLoai()) {
            model.addRow(new Object[]{
                item.getMaTheLoai(),
                item.getTenTheLoai()});
            cboTheLoai.addItem(item.getTenTheLoai());
        }

    }

    private void hienThiBangNhaXuatBan() {
        DefaultTableModel model = (DefaultTableModel) tblNhaXuatBan.getModel();
        model.setRowCount(0);
        for (NhaXuatBan item : new UserDAO().timNhaXuatBan()) {
            model.addRow(new Object[]{
                item.getMaNhaXuatBan(),
                item.getTenNhaXuatBan()});
            cboNhaXuatBan.addItem(item.getTenNhaXuatBan());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPopupMenu1 = new javax.swing.JPopupMenu();
        menuItemXoa = new javax.swing.JMenuItem();
        menuItemSua = new javax.swing.JMenuItem();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnlQuanLySach = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        cboTheLoai = new javax.swing.JComboBox<>();
        lblTenSach = new javax.swing.JLabel();
        lblTheLoai = new javax.swing.JLabel();
        lblNgayNhap = new javax.swing.JLabel();
        lblGiaTien = new javax.swing.JLabel();
        lblGiaTien1 = new javax.swing.JLabel();
        txtTenSach = new javax.swing.JTextField();
        txtNgayNhap = new javax.swing.JTextField();
        cboNhaXuatBan = new javax.swing.JComboBox<>();
        txtGiaTien = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        pnlThemSach = new javax.swing.JPanel();
        btnThemSach = new javax.swing.JButton();
        pnlHuySach = new javax.swing.JPanel();
        btnHuySach = new javax.swing.JButton();
        pnlSuaSach = new javax.swing.JPanel();
        btnSuaSach = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSach = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btnTimKiem = new javax.swing.JButton();
        txtTimKiem = new javax.swing.JTextField();
        btnLamMoi = new javax.swing.JButton();
        pnlTheLoai = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        lblTenSach1 = new javax.swing.JLabel();
        txtTenTheLoai = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        pnlThemTheLoai = new javax.swing.JPanel();
        btnThemTheLoai = new javax.swing.JButton();
        pnlHuyTheLoai = new javax.swing.JPanel();
        btnHuyTheLoai = new javax.swing.JButton();
        pnlSuaTheLoai = new javax.swing.JPanel();
        btnSuaTheLoai = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTheLoai = new javax.swing.JTable();
        pnlNhaXuatBan = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        lblTenSach2 = new javax.swing.JLabel();
        txtTenNhaXuatBan = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        pnlThemNhaXuatBan = new javax.swing.JPanel();
        btnThemNhaXuatBan = new javax.swing.JButton();
        pnlHuyNhaXuatBan = new javax.swing.JPanel();
        btnHuyNhaXuatBan = new javax.swing.JButton();
        pnlSuaNhaXuatBan = new javax.swing.JPanel();
        btnSuaNhaXuatBan = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblNhaXuatBan = new javax.swing.JTable();

        menuItemXoa.setText("Xóa");
        menuItemXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemXoaActionPerformed(evt);
            }
        });
        jPopupMenu1.add(menuItemXoa);

        menuItemSua.setText("Sửa");
        menuItemSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSuaActionPerformed(evt);
            }
        });
        jPopupMenu1.add(menuItemSua);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setLayout(new java.awt.GridBagLayout());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(23, 23, 23, 23);
        jPanel5.add(cboTheLoai, gridBagConstraints);

        lblTenSach.setText("Tên sách");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(23, 23, 23, 23);
        jPanel5.add(lblTenSach, gridBagConstraints);

        lblTheLoai.setText("Ngày nhập");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(23, 23, 23, 23);
        jPanel5.add(lblTheLoai, gridBagConstraints);

        lblNgayNhap.setText("Thể loại");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(23, 23, 23, 23);
        jPanel5.add(lblNgayNhap, gridBagConstraints);

        lblGiaTien.setText("Giá tiền");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(23, 23, 23, 23);
        jPanel5.add(lblGiaTien, gridBagConstraints);

        lblGiaTien1.setText("Nhà xuất bản");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(23, 23, 23, 23);
        jPanel5.add(lblGiaTien1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(23, 23, 23, 23);
        jPanel5.add(txtTenSach, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(23, 23, 23, 23);
        jPanel5.add(txtNgayNhap, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(23, 23, 23, 23);
        jPanel5.add(cboNhaXuatBan, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(23, 23, 23, 23);
        jPanel5.add(txtGiaTien, gridBagConstraints);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        pnlThemSach.setLayout(new java.awt.GridBagLayout());

        btnThemSach.setText("Thêm");
        btnThemSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemSachActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlThemSach.add(btnThemSach, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(pnlThemSach, gridBagConstraints);

        pnlHuySach.setLayout(new java.awt.GridBagLayout());

        btnHuySach.setText("Hủy");
        btnHuySach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuySachActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlHuySach.add(btnHuySach, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(pnlHuySach, gridBagConstraints);

        pnlSuaSach.setLayout(new java.awt.GridBagLayout());

        btnSuaSach.setText("Sửa");
        btnSuaSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaSachActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlSuaSach.add(btnSuaSach, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(pnlSuaSach, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.weightx = 1.0;
        jPanel5.add(jPanel1, gridBagConstraints);

        jPanel7.setLayout(new java.awt.BorderLayout());

        tblSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã sách", "Tên sách", "Thể loại", "Nhà xuất bản", "Ngày nhập", "Giá"
            }
        ));
        tblSach.setEditingColumn(0);
        tblSach.setEditingRow(0);
        tblSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSachMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSach);

        jPanel7.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        btnLamMoi.setText("Làm mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnTimKiem))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(btnLamMoi)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTimKiem)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout pnlQuanLySachLayout = new javax.swing.GroupLayout(pnlQuanLySach);
        pnlQuanLySach.setLayout(pnlQuanLySachLayout);
        pnlQuanLySachLayout.setHorizontalGroup(
            pnlQuanLySachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlQuanLySachLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlQuanLySachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlQuanLySachLayout.setVerticalGroup(
            pnlQuanLySachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlQuanLySachLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Quản lý sách", pnlQuanLySach);

        jPanel6.setLayout(new java.awt.GridBagLayout());

        lblTenSach1.setText("Tên thể loại");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(17, 17, 17, 17);
        jPanel6.add(lblTenSach1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(17, 17, 17, 17);
        jPanel6.add(txtTenTheLoai, gridBagConstraints);

        jPanel2.setLayout(new java.awt.GridBagLayout());

        pnlThemTheLoai.setLayout(new java.awt.GridBagLayout());

        btnThemTheLoai.setText("Thêm");
        btnThemTheLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemTheLoaiActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlThemTheLoai.add(btnThemTheLoai, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel2.add(pnlThemTheLoai, gridBagConstraints);

        pnlHuyTheLoai.setLayout(new java.awt.GridBagLayout());

        btnHuyTheLoai.setText("Hủy");
        btnHuyTheLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyTheLoaiActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlHuyTheLoai.add(btnHuyTheLoai, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel2.add(pnlHuyTheLoai, gridBagConstraints);

        pnlSuaTheLoai.setLayout(new java.awt.GridBagLayout());

        btnSuaTheLoai.setText("Sửa");
        btnSuaTheLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaTheLoaiActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlSuaTheLoai.add(btnSuaTheLoai, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel2.add(pnlSuaTheLoai, gridBagConstraints);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(0, 141, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(17, 17, 17, 17);
        jPanel6.add(jPanel8, gridBagConstraints);

        jPanel9.setLayout(new java.awt.BorderLayout());

        tblTheLoai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Mã thể loại", "Tên thể loại"
            }
        ));
        jScrollPane2.setViewportView(tblTheLoai);

        jPanel9.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout pnlTheLoaiLayout = new javax.swing.GroupLayout(pnlTheLoai);
        pnlTheLoai.setLayout(pnlTheLoaiLayout);
        pnlTheLoaiLayout.setHorizontalGroup(
            pnlTheLoaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTheLoaiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTheLoaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 903, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlTheLoaiLayout.setVerticalGroup(
            pnlTheLoaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTheLoaiLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Thể loại", pnlTheLoai);

        jPanel10.setLayout(new java.awt.GridBagLayout());

        lblTenSach2.setText("Nhà xuất bản");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(17, 17, 17, 17);
        jPanel10.add(lblTenSach2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(17, 17, 17, 17);
        jPanel10.add(txtTenNhaXuatBan, gridBagConstraints);

        jPanel4.setLayout(new java.awt.GridBagLayout());

        pnlThemNhaXuatBan.setLayout(new java.awt.GridBagLayout());

        btnThemNhaXuatBan.setText("Thêm");
        btnThemNhaXuatBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemNhaXuatBanActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlThemNhaXuatBan.add(btnThemNhaXuatBan, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel4.add(pnlThemNhaXuatBan, gridBagConstraints);

        pnlHuyNhaXuatBan.setLayout(new java.awt.GridBagLayout());

        btnHuyNhaXuatBan.setText("Hủy");
        btnHuyNhaXuatBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyNhaXuatBanActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlHuyNhaXuatBan.add(btnHuyNhaXuatBan, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel4.add(pnlHuyNhaXuatBan, gridBagConstraints);

        pnlSuaNhaXuatBan.setLayout(new java.awt.GridBagLayout());

        btnSuaNhaXuatBan.setText("Sửa");
        btnSuaNhaXuatBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaNhaXuatBanActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pnlSuaNhaXuatBan.add(btnSuaNhaXuatBan, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel4.add(pnlSuaNhaXuatBan, gridBagConstraints);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(0, 101, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(17, 17, 17, 17);
        jPanel10.add(jPanel11, gridBagConstraints);

        jPanel12.setLayout(new java.awt.BorderLayout());

        tblNhaXuatBan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Mã nhà xuất bản", "Tên nhà xuất bản"
            }
        ));
        jScrollPane3.setViewportView(tblNhaXuatBan);

        jPanel12.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout pnlNhaXuatBanLayout = new javax.swing.GroupLayout(pnlNhaXuatBan);
        pnlNhaXuatBan.setLayout(pnlNhaXuatBanLayout);
        pnlNhaXuatBanLayout.setHorizontalGroup(
            pnlNhaXuatBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNhaXuatBanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlNhaXuatBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, 903, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlNhaXuatBanLayout.setVerticalGroup(
            pnlNhaXuatBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNhaXuatBanLayout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Nhà xuất bản", pnlNhaXuatBan);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSuaActionPerformed
        pnlSuaSach.setVisible(true);
        pnlThemSach.setVisible(false);

    }//GEN-LAST:event_menuItemSuaActionPerformed

    private void menuItemXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemXoaActionPerformed
        UserDAO userDAO = new UserDAO();

        int dialogResult = JOptionPane.showConfirmDialog(null,
                "Bạn có muốn tiếp tục thực hiện câu lệnh không?",
                "Thông báo", JOptionPane.YES_NO_OPTION);
        if (dialogResult == JOptionPane.YES_OPTION) {
            try {
                userDAO.xoaSach(tblSach.getModel().getValueAt(tblSach.getSelectedRow(), 0).toString());
                hienThiBangSach();
            } catch (SQLException ex) {
                Logger.getLogger(Manager.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {

        }

    }//GEN-LAST:event_menuItemXoaActionPerformed

    private void btnSuaNhaXuatBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaNhaXuatBanActionPerformed

    }//GEN-LAST:event_btnSuaNhaXuatBanActionPerformed

    private void btnHuyNhaXuatBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyNhaXuatBanActionPerformed
        txtTenNhaXuatBan.setText("");
     }//GEN-LAST:event_btnHuyNhaXuatBanActionPerformed

    private void btnThemNhaXuatBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemNhaXuatBanActionPerformed
        String tenNhaXuatBan = txtTenNhaXuatBan.getText();
        if (tenNhaXuatBan.equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin nhà xuất bản!");
        } else {

            UserDAO userDAO = new UserDAO();
            try {
                userDAO.themNhaXuatBan(tenNhaXuatBan);
            } catch (SQLException ex) {
                Logger.getLogger(DangKyJPanel.class.getName()).log(Level.SEVERE, null, ex);
            }

            hienThiBangNhaXuatBan();
        }// TODO add your handling code here:
    }//GEN-LAST:event_btnThemNhaXuatBanActionPerformed

    private void btnSuaTheLoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaTheLoaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSuaTheLoaiActionPerformed

    private void btnHuyTheLoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyTheLoaiActionPerformed
        txtTenTheLoai.setText("");
    }//GEN-LAST:event_btnHuyTheLoaiActionPerformed

    private void btnThemTheLoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemTheLoaiActionPerformed
        String tenTheLoai = txtTenTheLoai.getText();
        if (tenTheLoai.equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin!");
        } else {

            UserDAO userDAO = new UserDAO();
            try {
                userDAO.themTheLoai(tenTheLoai);
            } catch (SQLException ex) {
                Logger.getLogger(DangKyJPanel.class.getName()).log(Level.SEVERE, null, ex);
            }

            hienThiBangTheLoai();
        }
    }//GEN-LAST:event_btnThemTheLoaiActionPerformed

    private void tblSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSachMouseClicked

        ArrayList<Object> list = new ArrayList<>();
        int i = tblSach.getSelectedRow();
        txtTenSach.setText(tblSach.getModel().getValueAt(i, 1).toString());
        cboTheLoai.setSelectedItem(tblSach.getModel().getValueAt(i, 2).toString());
        cboNhaXuatBan.setSelectedItem(tblSach.getModel().getValueAt(i, 3).toString());
        txtGiaTien.setText(String.valueOf(tblSach.getModel().getValueAt(i, 5)));
        System.out.println(i);
    }//GEN-LAST:event_tblSachMouseClicked

    private void btnSuaSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaSachActionPerformed
        String tenSach = txtTenSach.getText();
        String tenTheLoai = (String) cboTheLoai.getSelectedItem();
        String tenNhaXuatBan = (String) cboNhaXuatBan.getSelectedItem();
        String ngayNhap = txtNgayNhap.getText();
        float giaTien = Float.parseFloat(txtGiaTien.getText());

        if (tenSach.equals("") || tenTheLoai.equals("")
                || tenNhaXuatBan.equals("") || ngayNhap.equals("")
                || giaTien <= 0 || txtGiaTien.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin sách!");
        } else {

            UserDAO userDAO = new UserDAO();
            try {
                userDAO.suaSach(tblSach.getModel().getValueAt(tblSach.getSelectedRow(), 0).toString(),
                        tenSach, tenTheLoai, tenNhaXuatBan, ngayNhap, giaTien);

            } catch (SQLException ex) {
                Logger.getLogger(DangKyJPanel.class.getName()).log(Level.SEVERE, null, ex);
            }

            hienThiBangSach();
        }
    }//GEN-LAST:event_btnSuaSachActionPerformed

    private void btnHuySachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuySachActionPerformed
        resetDuLieuSach();
    }//GEN-LAST:event_btnHuySachActionPerformed

    private void btnThemSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemSachActionPerformed
        String tenSach = txtTenSach.getText();
        String tenTheLoai = (String) cboTheLoai.getSelectedItem();
        String tenNhaXuatBan = (String) cboNhaXuatBan.getSelectedItem();
        String ngayNhap = txtNgayNhap.getText();
        float giaTien = 0;
        try {
            giaTien = Float.parseFloat(txtGiaTien.getText());

        } catch (NumberFormatException ex) {

            JOptionPane.showMessageDialog(this, "Vui lòng nhập số.");
            txtGiaTien.setText("");
        }

        if (tenSach.equals("") || tenTheLoai.equals("")
                || tenNhaXuatBan.equals("") || ngayNhap.equals("")
                || giaTien <= 0 || txtGiaTien.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin sách!");
        } else {

            UserDAO userDAO = new UserDAO();
            try {
                userDAO.themSach(tenSach, tenTheLoai, tenNhaXuatBan, ngayNhap, giaTien);
            } catch (SQLException ex) {
                Logger.getLogger(DangKyJPanel.class.getName()).log(Level.SEVERE, null, ex);
            }

            hienThiBangSach();
        }
    }//GEN-LAST:event_btnThemSachActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        hienThiBangSach();
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
     

        DefaultTableModel model = (DefaultTableModel) tblSach.getModel();
        model.setRowCount(0);
        for (Sach item : new UserDAO().timSach(txtTimKiem.getText())) {
            model.addRow(new Object[]{
                item.getMaSach(),
                item.getTenSach(),
                item.getTenTheLoai(),
                item.getTenNhaXuatBan(),
                item.getNgayNhap(),
                item.getGiaTien()});
        }
    }//GEN-LAST:event_btnTimKiemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuyNhaXuatBan;
    private javax.swing.JButton btnHuySach;
    private javax.swing.JButton btnHuyTheLoai;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnSuaNhaXuatBan;
    private javax.swing.JButton btnSuaSach;
    private javax.swing.JButton btnSuaTheLoai;
    private javax.swing.JButton btnThemNhaXuatBan;
    private javax.swing.JButton btnThemSach;
    private javax.swing.JButton btnThemTheLoai;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JComboBox<String> cboNhaXuatBan;
    private javax.swing.JComboBox<String> cboTheLoai;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblGiaTien;
    private javax.swing.JLabel lblGiaTien1;
    private javax.swing.JLabel lblNgayNhap;
    private javax.swing.JLabel lblTenSach;
    private javax.swing.JLabel lblTenSach1;
    private javax.swing.JLabel lblTenSach2;
    private javax.swing.JLabel lblTheLoai;
    private javax.swing.JMenuItem menuItemSua;
    private javax.swing.JMenuItem menuItemXoa;
    private javax.swing.JPanel pnlHuyNhaXuatBan;
    private javax.swing.JPanel pnlHuySach;
    private javax.swing.JPanel pnlHuyTheLoai;
    private javax.swing.JPanel pnlNhaXuatBan;
    private javax.swing.JPanel pnlQuanLySach;
    private javax.swing.JPanel pnlSuaNhaXuatBan;
    private javax.swing.JPanel pnlSuaSach;
    private javax.swing.JPanel pnlSuaTheLoai;
    private javax.swing.JPanel pnlTheLoai;
    private javax.swing.JPanel pnlThemNhaXuatBan;
    private javax.swing.JPanel pnlThemSach;
    private javax.swing.JPanel pnlThemTheLoai;
    private javax.swing.JTable tblNhaXuatBan;
    private javax.swing.JTable tblSach;
    private javax.swing.JTable tblTheLoai;
    private javax.swing.JTextField txtGiaTien;
    private javax.swing.JTextField txtNgayNhap;
    private javax.swing.JTextField txtTenNhaXuatBan;
    private javax.swing.JTextField txtTenSach;
    private javax.swing.JTextField txtTenTheLoai;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
